# SPDX-License-Identifier: GPL-2.0-only
#
# Keira Kernel - Operating System Kernel
# Copyright (C) 2026 Moh. Ananda Firmansyah Putra
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.

[workspace]
members = [
    "crates/core",
    "crates/arch",
    "crates/crypto",
    "crates/mem",
    "crates/io",
    "crates/fs",
    "crates/net",
    "crates/task",
    "crates/ipc",
    "crates/syscall",
    "crates/shell",
    "crates/kernel",
]
resolver = "2"

[profile.dev]
panic = "abort"
lto = false
opt-level = 0
debug = true

[profile.release]
panic = "abort"
lto = true
opt-level = 3
codegen-units = 1
debug = false