# SPDX-License-Identifier: GPL-2.0-only
#
# Keira Kernel - Operating System Kernel
# Copyright (C) 2026 Moh. Ananda Firmansyah Putra
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.

[package]
name = "keira-kernel"
version = "0.33.7"
edition = "2021"
authors = ["Moh. Ananda Firmansyah Putra <mrvlous@proton.me>"]
license = "GPL-2.0-only"
description = "Master kernel assembly crate compiling into static library for Keira Kernel"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
keira-core = { path = "../core" }
keira-arch = { path = "../arch" }
keira-crypto = { path = "../crypto" }
keira-mem = { path = "../mem" }
keira-io = { path = "../io" }
keira-fs = { path = "../fs" }
keira-net = { path = "../net" }
keira-task = { path = "../task" }
keira-ipc = { path = "../ipc" }
keira-syscall = { path = "../syscall" }
keira-shell = { path = "../shell" }
